Feat: Node UI
nicktruong/chatbot-fe pull request #15
Opened 2024-03-01 08:51 UTC by nicktruong

### Tasks
- [Node UI](https://trello.com/c/zAARqzjC)

### Describe
- Build Node UI

### Screenshots
<img width="1510" alt="image" src="https://github.com/nicktruong/chatbot-fe/assets/154394020/454b12b0-6500-429f-a660-e48e77442c49">

2024-03-10 23:55 UTC, carl-huynh-goldenowl requested changes

2024-03-10 23:55 UTC, carl-huynh-goldenowl commented on src/app/pages/Studio/components/StandardNode/styles.ts
> +    _hover: { outline: '1.5px solid #0090ff' },
Should use this color as constant. Please check for other colors.

2024-03-11 03:03 UTC, nicktruong commented on src/app/pages/Studio/components/StandardNode/styles.ts
> +    _hover: { outline: '1.5px solid #0090ff' },
Some colors for `boxShadow` and some `rgba` colors are unique and can't be reuse so I won't refactor these as constants.
Other colors have been assigned as properties inside the `themes` object.

2024-03-12 02:02 UTC, carl-huynh-goldenowl approved these changes

2024-03-12 02:17 UTC, merged