Feat: Integrate API to get nodes from server on init
nicktruong/chatbot-fe pull request #16
Opened 2024-03-04 02:37 UTC by nicktruong

### Tasks
- [Node UI](https://trello.com/c/zAARqzjC)
- [Get all nodes API](https://trello.com/c/cTzzNgQ5)

### Describe
- Get all nodes on component mount

### Screenshots
<img width="1512" alt="image" src="https://github.com/nicktruong/chatbot-fe/assets/154394020/a38863ad-8d40-410e-a4a4-68d675e4d8b7">

2024-03-11 00:02 UTC, carl-huynh-goldenowl requested changes

2024-03-11 00:02 UTC, carl-huynh-goldenowl commented on src/app/pages/Studio/containers/Canvas/constants.ts
This file should be named containing `mapping`

2024-03-11 03:14 UTC, nicktruong commented on src/app/pages/Studio/components/Flows/helpers.ts
> +          isActive: flowType?.type === flow?.toUpperCase() || id === flow,
Hmm, I don't think I can reuse this anywhere else 🤔. Please help me to give an example how can I reuse this if I write this as a helper. Thank you 🙏.

2024-03-12 02:14 UTC, nicktruong commented on src/app/pages/Studio/components/Flows/helpers.ts
> +          isActive: flowType?.type === flow?.toUpperCase() || id === flow,
Done. Please have a review again @carl-huynh-goldenowl, thank you.

2024-03-13 01:59 UTC, merged