Feat: Edge apis integration
nicktruong/chatbot-fe pull request #24
Opened 2024-03-12 02:14 UTC by nicktruong

### Tasks
- [Edge APIs](https://trello.com/c/UjtgYdh7)

### Describe
- Extract `Card` component from `StandardNode`
- `Get` edges on cards and nodes load
- Integrate `Create` and `Update` edge api

### Demo videos
- https://drive.google.com/file/d/1O5gWTNmuu_XpmcDqYsNBzCb7148ewEuv/view?usp=drive_link

2024-03-14 02:55 UTC, carl-huynh-goldenowl requested changes

2024-03-14 02:55 UTC, carl-huynh-goldenowl commented on src/hooks/apiHooks/queries/useGetEdgeByCardId.ts
> +  type: 'card' | 'node';
We can use enum for this

2024-03-14 02:55 UTC, carl-huynh-goldenowl commented on src/app/pages/Studio/containers/Canvas/helpers.ts
> +            console.log(edge.data === newData);
Remove console.log if unnecessary

2024-03-14 02:55 UTC, carl-huynh-goldenowl commented on src/app/pages/Studio/components/Card/helpers.ts
> +      type: 'smoothstep',
Can we use enum for this?

2024-03-14 02:55 UTC, carl-huynh-goldenowl commented on src/app/pages/Studio/components/EndNode/helpers.ts
> +import { Edge, addEdge } from 'reactflow';
Check import order again

2024-03-21 02:22 UTC, nicktruong commented
Merging this branch after refactor based on comments.

2024-03-21 02:22 UTC, merged