Feat: Sidebar logic
nicktruong/chatbot-fe pull request #9
Opened 2024-02-23 07:39 UTC by nicktruong

### Tasks
- [Sidebar](https://trello.com/c/ffUhSXX9)
- [Home Page](https://trello.com/c/MxZy1vxh)

### Prerequisites
- https://github.com/nicktruong/chatbot-be/pull/3

### Describe
- Integrate sidebar with `create` chatbot api to create the bot's metadata
- Integrate sidebar with `getAll` chatbot api to get all bots and display on the sidebar
- Handle app navigation logic on component mount and on link click 

### Screenshots
<img width="1163" alt="image" src="https://github.com/nicktruong/chatbot-fe/assets/154394020/eb852aad-2108-4c28-8ae2-4b7d15681312">
<img width="1163" alt="image" src="https://github.com/nicktruong/chatbot-fe/assets/154394020/2722abc5-70eb-41ca-8759-f3101a28e891">
<img width="1164" alt="image" src="https://github.com/nicktruong/chatbot-fe/assets/154394020/5fec2fad-a883-4e54-8710-f670c29c2107">

2024-02-26 03:15 UTC, carl-huynh-goldenowl requested changes

2024-02-26 03:15 UTC, carl-huynh-goldenowl commented on src/hooks/apiHooks/mutations/useCreateBotMutation.ts
> +import type { AxiosError } from 'axios';
Should place this import in line 2

2024-02-26 03:15 UTC, carl-huynh-goldenowl commented on src/interfaces/Bot.ts
> +  publishDate: string;
Shoud we use publishDate in past simple?

2024-02-26 03:15 UTC, carl-huynh-goldenowl commented on src/app/pages/Home/components/SidebarContent/SidebarContent.tsx
> +            return (
Should write this as render function

2024-02-26 03:15 UTC, carl-huynh-goldenowl commented on src/app/pages/Home/components/SidebarContent/SidebarContent.tsx
> +    return <Navigate to={routes.chatbotDetail.replace(':id', bots[0].id)} />;
Should use `generatepath`
https://reactrouter.com/en/main/utils/generate-path

2024-02-26 10:07 UTC, nicktruong commented on src/hooks/apiHooks/mutations/useCreateBotMutation.ts
> +import type { AxiosError } from 'axios';
Edited in: https://github.com/nicktruong/chatbot-fe/pull/11/files#diff-896bcbb7f72db0ab29472c743c383acf583b9ecc6c1c2b7b0ddfc7447bc343b9R1-R8

2024-02-26 10:08 UTC, nicktruong commented on src/interfaces/Bot.ts
> +  publishDate: string;
I'll stick to `publishDate` as it is still correct and to be consistent with the backend side

2024-02-26 10:09 UTC, nicktruong commented on src/app/pages/Home/components/SidebarContent/SidebarContent.tsx
> +            return (
Edited in: https://github.com/nicktruong/chatbot-fe/pull/11/files#diff-40407a4ca35743b59214351056462342a5084b38006d2a1fc4077e232c3a8114R44-R85

2024-02-26 10:10 UTC, nicktruong commented on src/app/pages/Home/components/SidebarContent/SidebarContent.tsx
> +    return <Navigate to={routes.chatbotDetail.replace(':id', bots[0].id)} />;
Edited in: https://github.com/nicktruong/chatbot-fe/pull/11/files#diff-2ba6268d786c9535754dbe0961b97df7447511ba69de5025c1ce62932efadc68R25-R27

2024-02-27 02:34 UTC, carl-huynh-goldenowl approved these changes

2024-02-27 02:35 UTC, merged